language: node_js
cache: yarn
env:
  - NODE_ENV=production
node_js:
 - "8.9.0"
script:
 - npm run run-all
 - npm run report-compile
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./reports
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard